apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-onboarding-operator
  namespace: team-onboarding-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-onboarding-operator
  template:
    metadata:
      labels:
        app: team-onboarding-operator
    spec:
      serviceAccountName: team-onboarding-operator
      containers:
      - name: operator
        image: team-onboarding-operator:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "team-onboarding-operator"