apiVersion: v1
kind: ServiceAccount
metadata:
  name: team-onboarding-operator
  namespace: team-onboarding-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: team-onboarding-operator
rules:
- apiGroups: ["onboarding.k8s.io"]
  resources: ["teamonboardingapps", "teamonboardingapps/status", "teamonboardingapps/finalizers"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["namespaces", "services", "configmaps", "secrets", "persistentvolumeclaims"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: team-onboarding-operator
subjects:
- kind: ServiceAccount
  name: team-onboarding-operator
  namespace: team-onboarding-system
roleRef:
  kind: ClusterRole
  name: team-onboarding-operator
  apiGroup: rbac.authorization.k8s.io